name: Deploy to server
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Hola mundo
        run: cat hola.php

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps: 
      - name: Hola mundo2
        run: echo "Hola mundo segundo"              